
export const CP437_TABLE =
  "\0☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼" +
  " !\"#$%&'()*+,-./0123456789:;<=>?@ABC" +
  "DEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefg" +
  "hijklmnopqrstuvwxyz{|}~⌂Çüéâäàåçêëèïî" +
  "ìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒" +
  "▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓" +
  "╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ";


export const CP437_LABELS = [
  "null",
  "white smiling face",
  "black smiling face",
  "black heart suit",
  "black diamond suit",
  "black club suit",
  "black spade suit",
  "bullet",
  "inverse bullet",
  "white circle",
  "inverse white circle",
  "male sign",
  "female sign",
  "eighth note",
  "beamed eighth notes",
  "white sun with rays",
  "black right-pointing pointer",
  "black left-pointing pointer",
  "up down arrow",
  "double exclamation mark",
  "pilcrow sign",
  "section sign",
  "black rectangle",
  "up down arrow with base",
  "upwards arrow",
  "downwards arrow",
  "rightwards arrow",
  "leftwards arrow",
  "right angle",
  "left right arrow",
  "upwards filled arrow",
  "downwards filled arrow",
  "space",
  "exclamation mark",
  "quotation mark",
  "number sign",
  "dollar sign",
  "percent sign",
  "ampersand",
  "apostrophe",
  "left parenthesis",
  "right parenthesis",
  "asterisk",
  "plus sign",
  "comma",
  "hyphen-minus",
  "full stop",
  "slash",
  "digit zero",
  "digit one",
  "digit two",
  "digit three",
  "digit four",
  "digit five",
  "digit six",
  "digit seven",
  "digit eight",
  "digit nine",
  "colon",
  "semicolon",
  "less-than sign",
  "equals sign",
  "greater-than sign",
  "question mark",
  "at sign",
  "uppercase A",
  "uppercase B",
  "uppercase C",
  "uppercase D",
  "uppercase E",
  "uppercase F",
  "uppercase G",
  "uppercase H",
  "uppercase I",
  "uppercase J",
  "uppercase K",
  "uppercase L",
  "uppercase M",
  "uppercase N",
  "uppercase O",
  "uppercase P",
  "uppercase Q",
  "uppercase R",
  "uppercase S",
  "uppercase T",
  "uppercase U",
  "uppercase V",
  "uppercase W",
  "uppercase X",
  "uppercase Y",
  "uppercase Z",
  "left square bracket",
  "backslash",
  "right square bracket",
  "caret",
  "underscore",
  "grave accent",
  "lowercase a",
  "lowercase b",
  "lowercase c",
  "lowercase d",
  "lowercase e",
  "lowercase f",
  "lowercase g",
  "lowercase h",
  "lowercase i",
  "lowercase j",
  "lowercase k",
  "lowercase l",
  "lowercase m",
  "lowercase n",
  "lowercase o",
  "lowercase p",
  "lowercase q",
  "lowercase r",
  "lowercase s",
  "lowercase t",
  "lowercase u",
  "lowercase v",
  "lowercase w",
  "lowercase x",
  "lowercase y",
  "lowercase z",
  "left curly bracket",
  "vertical bar",
  "right curly bracket",
  "tilde",
  "house",
  "uppercase C with cedilla",
  "lowercase u with diaeresis",
  "lowercase e with acute",
  "lowercase a with circumflex",
  "lowercase a with diaeresis",
  "lowercase a with grave",
  "lowercase a with ring above",
  "lowercase c with cedilla",
  "lowercase e with circumflex",
  "lowercase e with diaeresis",
  "lowercase e with grave",
  "lowercase i with diaeresis",
  "lowercase i with circumflex",
  "lowercase i with grave",
  "uppercase A with diaeresis",
  "uppercase A with ring above",
  "uppercase E with acute",
  "lowercase ae",
  "uppercase AE",
  "lowercase o with circumflex",
  "lowercase o with diaeresis",
  "lowercase o with grave",
  "lowercase u with circumflex",
  "lowercase u with grave",
  "lowercase y with diaeresis",
  "uppercase O with diaeresis",
  "uppercase U with diaeresis",
  "cent sign",
  "pound sign",
  "yen sign",
  "peseta sign",
  "function sign",
  "lowercase a with acute",
  "lowercase i with acute",
  "lowercase o with acute",
  "lowercase u with acute",
  "lowercase n with tilde",
  "uppercase N with tilde",
  "feminine ordinal indicator",
  "masculine ordinal indicator",
  "inverted question mark",
  "not sign",
  "soft hyphen",
  "one-half",
  "one-quarter",
  "inverted exclamation mark",
  "left-pointing double angle quotation mark",
  "right-pointing double angle quotation mark",
  "light shade",
  "medium shade",
  "dark shade",

"box drawings light vertical",
"box drawings light vertical and left",
"box drawings vertical single and left double",
"box drawings vertical double and left single",
"box drawings down double and left single",
"box drawings down single and left double",
"box drawings double vertical and left",
"box drawings double vertical",
"box drawings double down and left",
"box drawings double up and left",
"box drawings up double and left single",
"box drawings up single and left double",
"box drawings light down and left",
"box drawings light up and right",
"box drawings light up and horizontal",
"box drawings light down and horizontal",
"box drawings light vertical and right",
"box drawings light horizontal",
"box drawings light vertical and horizontal",
"box drawings vertical single and right double",
"box drawings vertical double and right single",
"box drawings double up and right",
"box drawings double down and right",
"box drawings double up and horizontal",
"box drawings double down and horizontal",
"box drawings double vertical and right",
"box drawings double horizontal",
"box drawings double vertical and horizontal",
"box drawings up single and horizontal double",
"box drawings up double and horizontal single",
"box drawings down single and horizontal double",
"box drawings down double and horizontal single",
"box drawings up double and right single",
"box drawings up single and right double",
"box drawings down single and right double",
"box drawings down double and right single",
"box drawings vertical double and horizontal single",
"box drawings vertical single and horizontal double",
"box drawings light up and left",
"box drawings light down and right",




  "full block",
  "lower half block",
  "left half block",
  "right half block",
  "upper half block",
  "Greek alpha",
  "Greek beta / Sharp s",
  "Greek Gamma",
  "Greek pi",
  "Greek Sigma",
  "Greek sigma",
  "Greek mu",
  "Greek tau",
  "Greek Phi",
  "Greek Theta",
  "Greek Omega",
  "Greek delta",
  "infinity",
  "Greek phi",
  "Greek epsilon",
  "intersection",
  "identical to",
  "plus-minus sign",
  "greater-than or equal to",
  "less-than or equal to",
  "top half integral",
  "bottom half integral",
  "division sign",
  "approximately equal",
  "degree sign",
  "bullet operator",
  "middle dot",
  "square root",
  "superscript n",
  "superscript 2",
  "black square",
  "non-breakable space"
];
